name: Microservice CI pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  ci:
    permissions:
      contents: read
      packages: write

    uses: GamesBond-org/database/.github/workflows/reusable-workflow.yaml@develop
    with:
      image_name: player-service
      sonar_project_key: gamesbond-player-service
    secrets: inherit